/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafkaproducer.domain;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Sample extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5553377807221907158L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sample\",\"namespace\":\"com.example.kafkaproducer.domain\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"field1\",\"type\":\"string\"},{\"name\":\"field2\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Sample> ENCODER =
      new BinaryMessageEncoder<Sample>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Sample> DECODER =
      new BinaryMessageDecoder<Sample>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Sample> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Sample> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Sample>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Sample to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Sample from a ByteBuffer. */
  public static Sample fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence field1;
  @Deprecated public java.lang.CharSequence field2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sample() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param field1 The new value for field1
   * @param field2 The new value for field2
   */
  public Sample(java.lang.Integer id, java.lang.CharSequence field1, java.lang.CharSequence field2) {
    this.id = id;
    this.field1 = field1;
    this.field2 = field2;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return field1;
    case 2: return field2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: field1 = (java.lang.CharSequence)value$; break;
    case 2: field2 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'field1' field.
   * @return The value of the 'field1' field.
   */
  public java.lang.CharSequence getField1() {
    return field1;
  }

  /**
   * Sets the value of the 'field1' field.
   * @param value the value to set.
   */
  public void setField1(java.lang.CharSequence value) {
    this.field1 = value;
  }

  /**
   * Gets the value of the 'field2' field.
   * @return The value of the 'field2' field.
   */
  public java.lang.CharSequence getField2() {
    return field2;
  }

  /**
   * Sets the value of the 'field2' field.
   * @param value the value to set.
   */
  public void setField2(java.lang.CharSequence value) {
    this.field2 = value;
  }

  /**
   * Creates a new Sample RecordBuilder.
   * @return A new Sample RecordBuilder
   */
  public static com.example.kafkaproducer.domain.Sample.Builder newBuilder() {
    return new com.example.kafkaproducer.domain.Sample.Builder();
  }

  /**
   * Creates a new Sample RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sample RecordBuilder
   */
  public static com.example.kafkaproducer.domain.Sample.Builder newBuilder(com.example.kafkaproducer.domain.Sample.Builder other) {
    return new com.example.kafkaproducer.domain.Sample.Builder(other);
  }

  /**
   * Creates a new Sample RecordBuilder by copying an existing Sample instance.
   * @param other The existing instance to copy.
   * @return A new Sample RecordBuilder
   */
  public static com.example.kafkaproducer.domain.Sample.Builder newBuilder(com.example.kafkaproducer.domain.Sample other) {
    return new com.example.kafkaproducer.domain.Sample.Builder(other);
  }

  /**
   * RecordBuilder for Sample instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sample>
    implements org.apache.avro.data.RecordBuilder<Sample> {

    private int id;
    private java.lang.CharSequence field1;
    private java.lang.CharSequence field2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.kafkaproducer.domain.Sample.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.field1)) {
        this.field1 = data().deepCopy(fields()[1].schema(), other.field1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.field2)) {
        this.field2 = data().deepCopy(fields()[2].schema(), other.field2);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Sample instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.kafkaproducer.domain.Sample other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.field1)) {
        this.field1 = data().deepCopy(fields()[1].schema(), other.field1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.field2)) {
        this.field2 = data().deepCopy(fields()[2].schema(), other.field2);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.kafkaproducer.domain.Sample.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.kafkaproducer.domain.Sample.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'field1' field.
      * @return The value.
      */
    public java.lang.CharSequence getField1() {
      return field1;
    }

    /**
      * Sets the value of the 'field1' field.
      * @param value The value of 'field1'.
      * @return This builder.
      */
    public com.example.kafkaproducer.domain.Sample.Builder setField1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.field1 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'field1' field has been set.
      * @return True if the 'field1' field has been set, false otherwise.
      */
    public boolean hasField1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'field1' field.
      * @return This builder.
      */
    public com.example.kafkaproducer.domain.Sample.Builder clearField1() {
      field1 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'field2' field.
      * @return The value.
      */
    public java.lang.CharSequence getField2() {
      return field2;
    }

    /**
      * Sets the value of the 'field2' field.
      * @param value The value of 'field2'.
      * @return This builder.
      */
    public com.example.kafkaproducer.domain.Sample.Builder setField2(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.field2 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'field2' field has been set.
      * @return True if the 'field2' field has been set, false otherwise.
      */
    public boolean hasField2() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'field2' field.
      * @return This builder.
      */
    public com.example.kafkaproducer.domain.Sample.Builder clearField2() {
      field2 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Sample build() {
      try {
        Sample record = new Sample();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.field1 = fieldSetFlags()[1] ? this.field1 : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.field2 = fieldSetFlags()[2] ? this.field2 : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Sample>
    WRITER$ = (org.apache.avro.io.DatumWriter<Sample>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Sample>
    READER$ = (org.apache.avro.io.DatumReader<Sample>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
